deta_key = "c0z1mow5_PCxfeiUbf1rTPyGViv11u6Q2Zhmz7cbb"
author_password = "tDRYrXfLb9U21YSootTrvl17Aha60xXDUpn_a2lRKNQmG5Lxxo184QvevK_Au5gOiyPHfOr5TZ8xrZ5j1qEV3b3QU4XjrtLMS7HUD_oONrDhztCI9GLIxDE51ay2nnOUt4sZcxWQqBErOeoyxFa3mdC6w6xjtUeQu_kccz5LolWZ3stMFUTpxTalhcaLH3sR2phdedVVwKuRFTA_7iBGZYzNMwY0tSLjntF06LMWG4pkZJeszE6wW9UJ7IFQvRx8"
PushDeer_key = "PDU12177TM30DMBCR7Wg7SjzWd0dTKxubndtIbFlj"
YuQue_Token = "ntKlXuCZTgBicnxkdvYLSDcGkRnR2wKsZl4CpTUc"